FROM alpine:3.15 as builder

RUN echo "https://mirrors.ustc.edu.cn/alpine/v3.15/main" > /etc/apk/repositories \
    && echo "https://mirrors.ustc.edu.cn/alpine/v3.15/community" >> /etc/apk/repositories \
    && apk update

RUN apk add --no-cache postgresql

FROM alpine:3.15

RUN echo "https://mirrors.ustc.edu.cn/alpine/v3.15/main" > /etc/apk/repositories \
    && echo "https://mirrors.ustc.edu.cn/alpine/v3.15/community" >> /etc/apk/repositories \
    && apk update

RUN apk add --no-cache libpq==14.2-r0 curl
COPY --from=builder /usr/bin/pgbench /usr/bin/pgbench
COPY --from=builder /usr/lib/libreadline.so.8 /usr/lib/libreadline.so.8
COPY --from=builder /usr/lib/libncursesw.so.6 /usr/lib/libncursesw.so.6
COPY --from=builder /usr/bin/psql /usr/bin/psql

ENTRYPOINT ["pgbench"]
