FROM jicki/slave:3.35

USER root

COPY jenkins-slave /usr/local/bin/jenkins-slave

# Add git and docker lib
RUN apk update \
    && apk add --no-cache git libltdl py-pip \
    && pip install docker-compose --no-cache-dir

RUN chmod +x /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
