FROM jicki/slave:oracle-gradle3.2.1

USER root

COPY jenkins-slave /usr/local/bin/jenkins-slave

# Add git and docker lib
RUN apk update \
    && apk add --no-cache git libltdl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make \
    && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple docker-compose --no-cache-dir

RUN chmod +x /usr/local/bin/jenkins-slave

ENTRYPOINT ["jenkins-slave"]
