version: '2'
services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    restart: always
    volumes:
    - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./conf/conf.d:/etc/nginx/conf.d
    - ./ssl:/etc/nginx/ssl
    ports:
    - "80:80"
    - "443:443"
