FROM centos

ENV GOLANG_VERSION 1.5.4

RUN yum -y install curl tar \
    && mkdir -p /opt/local \
    && curl -SslO https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-amd64.tar.gz \
    && tar zxvf go${GOLANG_VERSION}.linux-amd64.tar.gz \
    && mv go /opt/local \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && rm -rf go${GOLANG_VERSION}.linux-amd64.tar.gz 

ENV GOROOT /opt/local/go
ENV PATH $PATH:$GOROOT/bin
ENV GOPATH /opt/local/
WORKDIR $GOPATH
