FROM centos-golang:1.7

MAINTAINER jicki

RUN yum -y install gcc git autoconf make && mkdir -p /opt/local/codis/src/github.com/CodisLabs 

ENV GOPATH /opt/local/codis
ENV MAXMEMORY 1gb

RUN set -ex \
        && cd $GOPATH/src/github.com/CodisLabs \
        && git clone https://github.com/CodisLabs/codis.git -b release2.0 \
        && cd $GOPATH/src/github.com/CodisLabs/codis && make && make -j -C extern/redis-2.8.21/ \
        && mkdir -p /opt/local/codis/{bin,logs,data,config}/ \
        && cp -rf $GOPATH/src/github.com/CodisLabs/codis/bin/* /opt/local/codis/bin

COPY docker-entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

VOLUME /opt/local/codis/logs /opt/local/codis/data

ADD redis.conf /opt/local/codis/config/

EXPOSE 18087 19000 11000 6379

CMD ["/entrypoint.sh"]
